language: php

php:
  - 7.2
  - 7.3

dist: trusty

addons:
  chrome: stable

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

service:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE ModuleUser;'

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction
  # install php extensions
  - |
    if (php --version | grep -i HipHop > /dev/null); then
      echo "Skipping imagick and gmagick tests on HHVM"
    else
      pear config-set preferred_state beta
      printf "\n" | pecl install imagick
    fi

before_script:
  - echo "Config required"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

  - echo "Download selenium-server-standalone jar file"
  - wget -c -nc --retry-connrefused --tries=0 https://bit.ly/2TlkRyu -O selenium-server-standalone.jar

  - echo "Download chromedriver"
  - wget https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
  - unzip -o -q chromedriver_linux64.zip

  - echo "Run selenium-server"
  - nohup bash -c "java -jar selenium-server-standalone.jar &" && sleep 1; cat nohup.out

  - vendor/bin/yii migrate --migrationPath=@TerabyteSoft/Module/User/Migrations --interactive=0

script:
  - |
    cd tests
    php -S 127.0.0.1:8080 -t public > /dev/null 2>&1&
    cd ..
    vendor/bin/codecept build
    vendor/bin/codecept run

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.3' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
    fi
